"""empty message

Revision ID: 2c3426639f97
Revises: f69a90742d81
Create Date: 2022-08-14 05:22:02.020133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3426639f97'
down_revision = 'f69a90742d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=500), nullable=True))
    op.execute("UPDATE venues SET website='http://napsui.herokuapp.com' WHERE website is NULL")
    op.execute("UPDATE artists SET website='http://napsui.herokuapp.com' WHERE website is NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
