"""empty message

Revision ID: 3f28226a970b
Revises: d17efa7639f2
Create Date: 2022-08-12 18:59:30.024520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f28226a970b'
down_revision = 'd17efa7639f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.execute('UPDATE artists SET seeking_venue=False WHERE seeking_venue is NULL')
    op.alter_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.execute('UPDATE venues SET seeking_talent=False WHERE seeking_talent is NULL')
    op.alter_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    
    # ### end Alembic commands ###
